# Settings that the LAMMPS build will import when this package library is used
# The default settings assume that HDF5 support is integrated into the standard
# distribution and search paths and thus only needs to link the HDF5 library.

h5md_SYSINC =-I/home1/xggong/zhouy/soft/anaconda/pkgs/hdf5-1.8.13-0/include/
h5md_SYSLIB = -lhdf5
h5md_SYSPATH =-L/home1/xggong/zhouy/soft/anaconda/pkgs/hdf5-1.8.13-0/lib
